// 一些全局的配置 比如html文件的路径 publicPath等
module.exports = {
  HTMLDirs:[
    "addindices",
    "addsms",
    "addStragety",
    "advertisement",
    "agency",
    "articlepublish",
    "bigscreenad",
    "code",
    "coin",
    "export",
    "feedback",
    "index",
    "login",
    "operatinganalysis",
    "pushmessage",
    "rebate",
    "searchkline",
    "singalmanage",
    "smsmanager",
    "stategymonitor",
    "stragypublish",
    "strategy",
    "tempmanager",
    "userbook",
    "usergroupid",
    "usermanage",
    "welcome"
  ],
  cssPublicPath:'../',
  imgOutputPath:'img/',
  fontOutputPath:'font/',
  cssOutputPath:'./css/styles.css',
  devServerOutputPath:'../dist',
  // apiPath:"http://127.0.0.1:8081/",
  apiPath:"http://172.16.137.247:8081/",
  // apiPathTest:'http://192.168.121.71:8080',
  imageServer:"/AlphaGu-admin"
};
